apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  annotations:
    cloudbees.io/trigger-id: test-trigger-buggy
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"tekton.dev/v1","kind":"TaskRun","metadata":{"annotations":{"cloudbees.io/trigger-id":"test-trigger-buggy"},"labels":{"cloudbees.io/component-id":"test-component","cloudbees.io/job":"test-job-buggy","cloudbees.io/organization":"test-org","cloudbees.io/pipeline-segment":"test-workflow-buggy","cloudbees.io/run-attempt":"1","cloudbees.io/run-id":"test-run-buggy","cloudbees.io/run-number":"1"},"name":"test-buggy-controller","namespace":"default"},"spec":{"taskSpec":{"steps":[{"image":"alpine:3.17","name":"hello","script":"#!/bin/sh\necho \"Testing BUGGY controller...\"\nsleep 5\necho \"Step completed successfully!\"\n"}]}}}
    pipeline.tekton.dev/release: 9db88e0
  creationTimestamp: "2026-03-19T22:36:40Z"
  finalizers:
  - taskrun.cloudbees.com/metrics-finalizer
  - taskrun.cloudbees.com/finalizer
  generation: 1
  labels:
    app.kubernetes.io/managed-by: tekton-pipelines
    cloudbees.io/component-id: test-component
    cloudbees.io/job: test-job-buggy
    cloudbees.io/organization: test-org
    cloudbees.io/pipeline-segment: test-workflow-buggy
    cloudbees.io/run-attempt: "1"
    cloudbees.io/run-id: test-run-buggy
    cloudbees.io/run-number: "1"
  name: test-buggy-controller
  namespace: default
  resourceVersion: "17061"
  uid: 47f49c1e-37fc-4ae6-849d-33bb63b8289b
spec:
  serviceAccountName: default
  taskSpec:
    steps:
    - computeResources: {}
      image: alpine:3.17
      name: hello
      script: |
        #!/bin/sh
        echo "Testing BUGGY controller..."
        sleep 5
        echo "Step completed successfully!"
  timeout: 1h0m0s
status:
  artifacts: {}
  completionTime: "2026-03-19T22:36:50Z"
  conditions:
  - lastTransitionTime: "2026-03-19T22:36:50Z"
    message: '{"hello":{"end":"2026-03-19T22:36:49Z"}}'
    status: "True"
    type: ReportedStepsStatus
  - lastTransitionTime: "2026-03-19T22:36:50Z"
    message: All Steps have completed executing
    reason: Succeeded
    status: "True"
    type: Succeeded
  - lastTransitionTime: "2026-03-19T22:36:40Z"
    message: "2026-03-19T22:36:40Z"
    status: "True"
    type: TaskActualStartTime
  - lastTransitionTime: "2026-03-19T22:36:40Z"
    message: "0"
    status: "True"
    type: TaskBuildMinutes
  podName: test-buggy-controller-pod
  provenance:
    featureFlags:
      awaitSidecarReadiness: true
      coschedule: workspaces
      enableAPIFields: alpha
      enableProvenanceInStatus: true
      enforceNonfalsifiability: none
      maxResultSize: 4096
      resultExtractionMethod: termination-message
      runningInEnvWithInjectedSidecars: true
      verificationNoMatchPolicy: ignore
  startTime: "2026-03-19T22:36:40Z"
  steps:
  - container: step-hello
    imageID: docker.io/library/alpine@sha256:8fc3dacfb6d69da8d44e42390de777e48577085db99aa4e4af35f483eb08b989
    name: hello
    provenance: {}
    terminated:
      containerID: containerd://333a496641ee94646c0c5400abd36fba3367f6bb5bee07ae75f71ff94f5c6829
      exitCode: 0
      finishedAt: "2026-03-19T22:36:49Z"
      reason: Completed
      startedAt: "2026-03-19T22:36:44Z"
    terminationReason: Completed
  taskSpec:
    steps:
    - computeResources: {}
      image: alpine:3.17
      name: hello
      script: |
        #!/bin/sh
        echo "Testing BUGGY controller..."
        sleep 5
        echo "Step completed successfully!"
